import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#00deec',
        'primary-dim': '#00deec',
        'primary-fixed': '#00eefc',
        'secondary-fixed': '#e4c6ff',
        'on-secondary': '#32005c',
        'on-secondary-container': '#f0dcff',
        'error-dim': '#d7383b',
        'on-error-container': '#ffa8a3',
        'tertiary': '#afffd1',
        'surface-dim': '#0e0e0e',
        'surface-container': '#1a1919',
        'outline-variant': '#494847',
        'error-container': '#9f0519',
        'on-primary-fixed-variant': '#005e64',
        'on-tertiary': '#006642',
        'on-surface-variant': '#adaaaa',
        'background': '#0e0e0e',
        'error': '#ff716c',
        'secondary-dim': '#9c42f4',
        'on-tertiary-fixed': '#00472d',
        'secondary-container': '#7701d0',
        'primary-container': '#00eefc',
        'on-surface': '#ffffff',
        'on-secondary-fixed-variant': '#7500cc',
        'secondary': '#bf81ff',
        'surface-bright': '#2c2c2c',
        'on-primary-fixed': '#003f43',
        'inverse-surface': '#fcf8f8',
        'on-primary': '#005d63',
        'on-error': '#490006',
        'tertiary-fixed-dim': '#00efa0',
        'on-background': '#ffffff',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'on-primary-container': '#005359',
        'tertiary-container': '#00ffab',
        'inverse-primary': '#006a71',
        'surface-variant': '#262626',
        'on-tertiary-container': '#005c3b',
        'inverse-on-surface': '#565554',
        'primary': '#8ff5ff',
        'surface-container-highest': '#262626',
        'on-secondary-fixed': '#4e008a',
        'outline': '#777575',
        'surface-tint': '#8ff5ff',
        'surface-container-high': '#201f1f',
        'on-tertiary-fixed-variant': '#006742',
        'surface': '#0e0e0e',
        'tertiary-dim': '#00efa0',
        'tertiary-fixed': '#00ffab',
        'secondary-fixed-dim': '#dab4ff'
      },
      fontFamily: {
        'headline': ['var(--font-headline)', 'sans-serif'],
        'body': ['var(--font-body)', 'sans-serif'],
        'label': ['var(--font-body)', 'sans-serif'],
        'mono': ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      keyframes: {
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInTop: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(143, 245, 255, 0.2)' },
          '50%': { boxShadow: '0 0 20px rgba(143, 245, 255, 0.5)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(143, 245, 255, 0.2)' },
          '50%': { boxShadow: '0 0 25px rgba(143, 245, 255, 0.4)' },
        },
        sweep: {
          '0%': { left: '-100%' },
          '100%': { left: '100%' },
        },
      },
      animation: {
        slideInLeft: 'slideInLeft 0.3s ease-out',
        slideInTop: 'slideInTop 0.4s ease-out',
        fadeIn: 'fadeIn 0.3s ease-in',
        glow: 'glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        pulseGlow: 'pulseGlow 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        sweep: 'sweep 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;